require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TransactionTypesController do

  def mock_transaction_type(stubs={})
    @mock_transaction_type ||= mock_model(TransactionType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all transaction_types as @transaction_types" do
      TransactionType.stub(:all) { [mock_transaction_type] }
      get :index
      assigns(:transaction_types).should eq([mock_transaction_type])
    end
  end

  describe "GET show" do
    it "assigns the requested transaction_type as @transaction_type" do
      TransactionType.stub(:find).with("37") { mock_transaction_type }
      get :show, :id => "37"
      assigns(:transaction_type).should be(mock_transaction_type)
    end
  end

  describe "GET new" do
    it "assigns a new transaction_type as @transaction_type" do
      TransactionType.stub(:new) { mock_transaction_type }
      get :new
      assigns(:transaction_type).should be(mock_transaction_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested transaction_type as @transaction_type" do
      TransactionType.stub(:find).with("37") { mock_transaction_type }
      get :edit, :id => "37"
      assigns(:transaction_type).should be(mock_transaction_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created transaction_type as @transaction_type" do
        TransactionType.stub(:new).with({'these' => 'params'}) { mock_transaction_type(:save => true) }
        post :create, :transaction_type => {'these' => 'params'}
        assigns(:transaction_type).should be(mock_transaction_type)
      end

      it "redirects to the created transaction_type" do
        TransactionType.stub(:new) { mock_transaction_type(:save => true) }
        post :create, :transaction_type => {}
        response.should redirect_to(transaction_type_url(mock_transaction_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transaction_type as @transaction_type" do
        TransactionType.stub(:new).with({'these' => 'params'}) { mock_transaction_type(:save => false) }
        post :create, :transaction_type => {'these' => 'params'}
        assigns(:transaction_type).should be(mock_transaction_type)
      end

      it "re-renders the 'new' template" do
        TransactionType.stub(:new) { mock_transaction_type(:save => false) }
        post :create, :transaction_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transaction_type" do
        TransactionType.stub(:find).with("37") { mock_transaction_type }
        mock_transaction_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :transaction_type => {'these' => 'params'}
      end

      it "assigns the requested transaction_type as @transaction_type" do
        TransactionType.stub(:find) { mock_transaction_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:transaction_type).should be(mock_transaction_type)
      end

      it "redirects to the transaction_type" do
        TransactionType.stub(:find) { mock_transaction_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(transaction_type_url(mock_transaction_type))
      end
    end

    describe "with invalid params" do
      it "assigns the transaction_type as @transaction_type" do
        TransactionType.stub(:find) { mock_transaction_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:transaction_type).should be(mock_transaction_type)
      end

      it "re-renders the 'edit' template" do
        TransactionType.stub(:find) { mock_transaction_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transaction_type" do
      TransactionType.stub(:find).with("37") { mock_transaction_type }
      mock_transaction_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the transaction_types list" do
      TransactionType.stub(:find) { mock_transaction_type }
      delete :destroy, :id => "1"
      response.should redirect_to(transaction_types_url)
    end
  end

end
